### PR TITLE
claim #32 + #12

### PR DESCRIPTION
**Pull request by rutikthakre**
As discussed here https://github.com/eronka/culero-api/pull/20
/claim #7

### CODE REVIEW

**Comment by rutikthakre** [comment]
Hi @hsb1007 is everything good to merge?

**Comment by KR1Z00** [comment]
Hi @Rutik7066, in general, I have noticed:

- There is no documentation for any of these widget classes. It would be far better to follow a best coding practice where all classes should have at least a one liner documentation comment explaining what it is for and what it does.
- The naming of related types is inconsistent. For example, we have 'card' widgets, 'tile' widgets, and 'item' widgets.
- Some widget classes don't have names that clearly indicate they are a widget. For example, `LatestReviewItem`. `EmailIsVerfied`.
- We should use proper Flutter `Theme`, ThemeData`, and `TextTheme` usage to ensure consistency across all widgets, and scalability of the codebase.
- Some classes don't have their parameters passed in and instead had internally hard-coded values for things such as `String`s or `double`s to be presented to the user.

**Comment by rutikthakre** [comment]
Hi @KR1Z00 I have your read the issues. I was assigned for atomic components in atom sir you can see the all basic components for project like typography, buttons and etc, then as @hsb1007 and I discussed I had to write code for molecules layer as well. so as per naming convention I tried to name the components as it can be identified by UI so it will be easy for developer to navigate through the components instead of figuring out by themselves. And I have hard coded values for landing page only could you please mark in code if you see any where in code.

**Comment by rutikthakre** [comment]
Hi @KR1Z00 emailisverified is page please check directory and routes

**Comment by rutikthakre** [comment]
Hey @KR1Z00 your themedata suggestions quit cool let me quickly update the code

**Comment by rutikthakre** [comment]
Done @KR1Z00

**Comment by rutikthakre** [comment]
Hi @KR1Z00 @hsb1007  may I know your timezone and working time in order to communicate properly.

**Comment by rutikthakre** [comment]
Hi @KR1Z00 could please take a look?

**Comment by rutikthakre** [comment]
@KR1Z00  isn't it good to merge?

**Comment by rutikthakre** [comment]
Hi @KR1Z00 @anehzat @hsb1007 I am waiting for your response.

**Comment by hsb1007** [comment]
Hi @Rutik7066 

No @KR1Z00 is reviewing the code and we are doing some work to establish some standard to put in place first then your PR can be updated to follow the standard

Will give you update soon!

**Comment by rutikthakre** [comment]
Ok @hsb1007 may I know how much time will it take?

**Comment by Rutik7066** [comment]
Can @hsb1007 you reward me now I guarantee you. I will make changes as per your requirement. Later as well on the PR

**Comment by rutikthakre** [comment]
@hsb1007 has any one reviewed the code? If any changes needed let me know. And what your thoughts about 
Landing page

**Comment by rutikthakre** [comment]
@hsb1007 @anehzat @KR1Z00  have you decided the standards to contribute?  
Are we good to go?

**Comment by hsb1007** [comment]
Hi Rutik, 

We have general base structure merged in. Could you please review to adjust your code into the structure we have? especially around the themeing so that it is scalable?

@KR1Z00 will review and validate it!

**Comment by rutikthakre** [comment]
Hi @hsb1007, 

Apologies, Repository is empty. I don't understand what are you talking about and I have added theming after last review from @KR1Z00 and some other changes as well. I was waiting for @KR1Z00 to review it. Could you please ask @KR1Z00 to review the latest changes and feedback me. I can understand and work well.

**Comment by hsb1007** [comment]
They are in develop branch!

**Comment by rutikthakre** [comment]
Hi @KR1Z00 @hsb1007  Updated the changes as asked. it is ready to review.

**Comment by KR1Z00** [comment]
Hi @Rutik7066 can you please git rebase your branch on top of the latest `develop` branch.

Aside from this:
1. It seems a lot of the comments above have not been addressed regarding coding practices.
2. We have noticed that the UI is not adaptive for smaller screens e.g. tablet and mobile.
3. We have noticed there are a lot of compiler warnings - a lot of them are due to redundant imports etc.

Screenshot 2024-04-05 at 10 05 02 AM

Screenshot 2024-04-04 at 11 46 54 AM

**Comment by hsb1007** [comment]
@KR1Z00 Thank you for the feedback.

@Rutik7066  KR1Z00 and I had a chat. Unfortunately, we won't be able to use the code unless the quality of the codes is well scalable. 

Let me know whether / when we can improve the PRs

**Comment by rutikthakre** [comment]
> Hi @Rutik7066 can you please git rebase your branch on top of the latest `develop` branch.
> 
> Aside from this:
> 1. It seems a lot of the comments above have not been addressed regarding coding practices.
> 2. We have noticed that the UI is not adaptive for smaller screens e.g. tablet and mobile.
> 3. We have noticed there are a lot of compiler warnings - a lot of them are due to redundant imports etc.
> 
> Screenshot 2024-04-05 at 10 05 02 AM
> 
> Screenshot 2024-04-04 at 11 46 54 AM
> 


Hi @KR1Z00 could you please tell me which comments exactly needs to be addressed

**Comment by Rutik7066** [comment]
It would be helpful for me if make comments on the code @KR1Z00

**Comment by hsb1007** [comment]
> > Hi @Rutik7066 can you please git rebase your branch on top of the latest `develop` branch.
> > 
> > Aside from this:
> > 1. It seems a lot of the comments above have not been addressed regarding coding practices.
> > 2. We have noticed that the UI is not adaptive for smaller screens e.g. tablet and mobile.
> > 3. We have noticed there are a lot of compiler warnings - a lot of them are due to redundant imports etc.
> > 
> > Screenshot 2024-04-05 at 10 05 02 AM
> > 
> > Screenshot 2024-04-04 at 11 46 54 AM
> > 
> 
> 
> Hi @KR1Z00 could you please tell me which comments exactly needs to be addressed 

Hi Rutik,

In fact all the comments he made need to be addressed

**Comment by rutikthakre** [comment]
Ok I will start working on it.

**Comment by hsb1007** [comment]
> Ok I will start working on it.

Hi @Rutik7066  How are you coming along? and when do you think you can finalise it?

Thanks

**Comment by rutikthakre** [comment]
hi @hsb1007 i can finalise it today only one point remained about coding practice 

> Hi @Rutik7066, in general, I have noticed:
> 
> * There is no documentation for any of these widget classes. It would be far better to follow a best coding practice where all classes should have at least a one liner documentation comment explaining what it is for and what it does.
> * The naming of related types is inconsistent. For example, we have 'card' widgets, 'tile' widgets, and 'item' widgets.
> * Some widget classes don't have names that clearly indicate they are a widget. For example, `LatestReviewItem`. `EmailIsVerfied`.
> * We should use proper Flutter `Theme`, ThemeData`, and `TextTheme` usage to ensure consistency across all widgets, and scalability of the codebase.
> * Some classes don't have their parameters passed in and instead had internally hard-coded values for things such as `String`s or `double`s to be presented to the user.

**Comment by rutikthakre** [comment]
About naming the components. i am not sure. how to name it. i hope @KR1Z00 will help me.

**Comment by rutikthakre** [comment]
Hi @KR1Z00  code is ready to review.

**Comment by rutikthakre** [comment]
@hsb1007 code is ready.

**Comment by hsb1007** [comment]
@KR1Z00  Hi Jamie! Would you be able to reiveiw please!

**Comment by rutikthakre** [comment]
Hi @hsb1007 @anehzat @KR1Z00  have you reviewed the PR.

**Comment by rutikthakre** [comment]
Hi @KR1Z00 @hsb1007 @anehzat PR is ready to review. I have added all the changes asked by Jamie. Added documentation as well. I just wanted to let you know that everything is done. It can be merged now.

**Comment by hsb1007** [comment]
> Hi @KR1Z00 @hsb1007 @anehzat PR is ready to review. I have added all the changes asked by Jamie. Added documentation as well. I just wanted to let you know that everything is done. It can be merged now.

Hi Rutik, 

Can you please make the screen 'responsive' rather than just disabling the styling?

**Comment by rutikthakre** [comment]
which one ?

**Comment by rutikthakre** [comment]
Hi, @hsb1007  Could you please create another issue for Main screen responsiveness and share the design for mobile devices? 
There wasn't any responsive design for the Main screen when I aked for this issue.

**Comment by rutikthakre** [comment]
> Hi, @hsb1007  Could you please create another issue for Main screen responsiveness and share the design for mobile devices? 
> There wasn't any responsive design for the Main screen when I aked for this issue.

Hi @KR1Z00 @hsb1007 @anehzat   could you please review the code as soon as possible.

**Comment by hsb1007** [comment]
Hi Rutik, have you had this issue to run it on ios?

image

**Comment by rutikthakre** [comment]
@hsb1007  I am on windows.

**Comment by rutikthakre** [comment]
@hsb1007 Are able to run flutter project?

**Comment by hsb1007** [comment]
No I can't run it on my phone for some reason, and I am troubleshotting

**Comment by hsb1007** [comment]
Hi @Rutik7066 on phone it doesn't load properly

image

**Comment by rutikthakre** [comment]
@hsb1007 Do you see any mobile screen design for this page

**Comment by hsb1007** [comment]
No I can't see any mobile screen, how do I get it to show mobile screen?

**Comment by rutikthakre** [comment]
@hsb1007  click on Sign up button

**Comment by rutikthakre** [comment]
@hsb1007  Is everything fine now? can we merge this PR.

**Pull request merged**
