### PR TITLE
feat: Flutter to have general structure to do API call and connect us…

### LINKED ISSUE #12: Flutter to have general structure to do API call and connect user registration / login API to current project
Flutter to have general structure to do API call and connect user registration / login API to current project

### PR DESCRIPTION
**Pull request by Bhavyajain21**
/fixes #12 
/claim #12

### CODE REVIEW

**Comment by Bhavyajain21** [comment]
Please review @hsb1007

**Comment by Bhavyajain21** [comment]
Adding screenshot:

image

**Comment by neo773** [comment]
You ripped off my PR for the 2nd time, not cool.
Ref PR:
https://github.com/tailcallhq/tailcallhq.github.io/pull/127

**Comment by Bhavyajain21** [comment]
I understand there was confusion regarding this GitHub issue and the overlapping PRs. I'm sorry for the misunderstanding. Since we both worked on similar code, let's find a way to collaborate and ensure everyone gets credit for their contributions. I'd like to discuss how we can resolve this together and avoid such situations in the future. @neo773 

PS: I already was been assigned on this issue before.

**Pull request closed without merging**
