### PR TITLE
Authentication integration

### PR DESCRIPTION
**Pull request by neo773**
This PR adds authentication integration with backend.

Checklist:
- Sign In
- Sign Up
- Persisted State (works after relaunching App)

Demo
https://github.com/eronka/culero-client/assets/62795688/f1896bf7-d26f-4f57-a039-ff7d096de413

PR depends on 
https://github.com/eronka/culero-api/pull/69

/claim #12

### CODE REVIEW

**Comment by hsb1007** [comment]
@neo773  Just so you know I am checking your PR and reward if everything is okay

Thank you for your contribution

**Comment by hsb1007** [comment]
Would you be able to connect to this API please!
https://stage.api.culero.com/docs (currently down but in process to be set up and running)
https://api2.culero.com/docs  (currently down but in process to be set up and running)

**Comment by neo773** [comment]
Hi,

You can simply swap the URL here to test with your live server

https://github.com/eronka/culero-client/pull/15/files#diff-f3c91690438b642f43b343956f4faf99763444f927c3805fd9690a87b6fe582bR10

**Comment by neo773** [comment]
But sign up won't work since it requires this PR to be merged first 
https://github.com/eronka/culero-api/pull/69

**Comment by hsb1007** [comment]
Please feel free to join our discord channel for easier comms! 

https://discord.gg/tyaRVrJsDW

**Comment by hsb1007** [comment]
I have tried updating the base url to api2.culero.com 
i get 404

**Pull request merged**
